#!/bin/bash
### BEGIN INIT INFO
# Provides:          power
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run efergy power script
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    log_begin_msg "Starting efergy power script"
    /home/pi/power/power.sh &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping efergy script"

    # do something to kill the service or cleanup or nothing
    killall -QUIT rtl_fm
    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/power {start|stop}"
    exit 1
    ;;
esac

